import express from 'express';
import multer from 'multer';
import cloudinary from 'cloudinary';

// cloudinary config
const cloudinary = new cloudinary();
AWS.config.update(
  {
    accessKeyId: process.env.CLOUDINARY_KEY,
    secretAccessKey: process.env.CLOUDINARY_SECRET,
    cloudinaryName: process.env.CLOUD_NAME
  });

const router = new express.Router();

// Multer config
// memory storage keeps file data in a buffer
const upload = multer({
  storage: multer.memoryStorage(),
  // file size limitation in bytes
  limits: { fileSize: 52428800 },
});

router.post('/upload', upload.single('file'), (req, res) => {
  File upload (example for promise api)
    cloudinary.uploader.upload(file)
    .then(function(image){
      console.log();
      console.log("** File Upload (Promise)");
      console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
      console.log("* "+image.public_id);
      console.log("* "+image.url);
    })
    .catch(function(err){
      console.log();
      console.log("** File Upload (Promise)");
      if (err){ console.warn(err);}
    });

//   cloudinary.uploader.upload.putObject({
//       Bucket: 'your-bucket-name',
//       Key: 'your-key-name',
//       Body: req.file.buffer,
//       ACL: 'public-read', // your permisions
//     }, (err) => {
//       if (err) return res.status(400).send(err);
//       res.send('File uploaded to S3');
})

module.exports = router;
